meta_name: "Diana Spieser"
meta_title: "Diana Spieser Portfolio"
meta_description: "DÃ©veloppeuse web Full stack, Programmation web front end HTML, CSS, JavaScript, Programmation back end en pattern MVC (Ruby en Rails)"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@Dianas57655855S"   # required for Twitter Cards
